const fs = require("fs");
const L = [];
L.push("# ITER3_O2 -- Deep Code Audit (Commits 8df34c3, e594193, fa63b46)");
L.push("");
L.push("Observer O2 - Iteration 3 - 2026-04-18");
L.push("");
L.push("---");
L.push("");
L.push("## Top 3 Urgent Fixes");
L.push("");
L.push("### 1. [CRITICAL] Counter-offer send/receive IDs are swapped -- every counter silently fails");
L.push("");
L.push("**File:** `app/trades.py:396-400` + `app/ai_gm.py:599-602`");
L.push("");
L.push("**Bug:** `maybe_counter()` returns `send_player_ids` and `receive_player_ids` from the");
L.push("**original trade perspective** (send = original sender players, receive = AI players).");
L.push("But `auto_decide_ai` calls `propose()` with `from_team=trade.to_team` (AI) and passes");
L.push("`send_ids=counter_dict[send_player_ids]` -- which are the **original sender (Human) players**.");
L.push("");
L.push("`propose()` validates `send_ids` against the new `from_team` (AI) roster at line 174-176.");
L.push("Human player IDs will not exist on the AI roster, raising");
L.push("`ValueError(Player {pid} not on proposer roster)`. The exception is caught at line 407,");
L.push("logged to stderr, and swallowed. The original trade is already moved to history as");
L.push("countered (line 391-393, **before** the try block), so the trade vanishes -- marked");
L.push("countered with no counter-offer ever created.");
L.push("");
L.push("**Repro:** Any AI counter-offer attempt. The 30% trigger fires, original trade disappears,");
L.push("no counter trade materializes.");
L.push("");
L.push("**Fix:** Swap the IDs when calling `propose()`:");
L.push("");
L.push("```python");
L.push("counter_trade = self.propose(");
L.push("    from_team=trade.to_team,");
L.push("    to_team=trade.from_team,");
L.push("    send_ids=counter_dict[receive_player_ids],   # AI players (now the sender)");
L.push("    receive_ids=counter_dict[send_player_ids],    # Human players (now the receiver)");
L.push("    ...");
L.push(")");
L.push("```");
L.push("");
L.push("OR fix `maybe_counter()` to return IDs from the counter-proposer perspective.");
fs.writeFileSync("D:/claude/fantasy nba/tests/ITER3_O2.md", L.join("\n") + "\n", "utf-8");
console.log("part1 ok", L.length);
